# Scaling
**Goal:** Process raw market data into a comprehensive feature set for ML training.

1.  **Data Validation:** Flag features with distribution drifts or high NaN rates.
2.  **Scaling:** Apply Robust Z-scaling and Time-features relative to market sessions.
3.  
**Output:** Saves a fully featured, scaled dataset to `feat_all.parquet`.

In [1]:
# 1) WIPE & PURGE
%reset -f
import gc
import torch
gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

# 2) IMPORTS
import os
import psutil
import importlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.auto import tqdm
from IPython.display import display

# Standardize display
pd.set_option('display.max_columns', None)

# 3) CUSTOM LIBRARIES
from libs import preps, plots, params, feats
importlib.reload(preps)
importlib.reload(plots)
importlib.reload(params)
importlib.reload(feats)

print(f"🚀 Memory Cleaned. Environment Ready for {params.ticker}")

🚀 Memory Cleaned. Environment Ready for AAPL

In [2]:
# Load raw data from the previous notebook's output

df_inds_unsc = pd.read_parquet(params.indunsc_parquet)

df_inds_unsc

,open,high,low,close,volume,trade_count,vwap,ask,bid,ret,log_ret,body,upper_shad,lower_shad,range_pct,sma_5,sma_pct_5,sma_9,sma_pct_9,sma_21,sma_pct_21,sma_50,sma_pct_50,sma_100,sma_pct_100,ema_3,ema_5,ema_9,ema_13,ema_21,ema_50,rsi_3,rsi_7,rsi_14,rsi_21,roc_3,roc_5,roc_10,roc_21,cci_7,cci_14,cci_20,macd_line_3_10_4,macd_signal_3_10_4,macd_diff_3_10_4,macd_line_6_13_5,macd_signal_6_13_5,macd_diff_6_13_5,macd_line_12_26_9,macd_signal_12_26_9,macd_diff_12_26_9,stoch_k_5_3_3,stoch_d_5_3_3,stoch_k_14_3_3,stoch_d_14_3_3,atr_3,atr_pct_3,plus_di_3,minus_di_3,adx_3,atr_7,atr_pct_7,plus_di_7,minus_di_7,adx_7,atr_14,atr_pct_14,plus_di_14,minus_di_14,adx_14,atr_21,atr_pct_21,plus_di_21,minus_di_21,adx_21,bb_lband_20_2p0,bb_hband_20_2p0,bb_w_20_2p0,bb_lband_20_3p0,bb_hband_20_3p0,bb_w_20_3p0,bb_lband_50_2p0,bb_hband_50_2p0,bb_w_50_2p0,kc_mid_20_20_1.5,kc_l_20_20_1.5,kc_h_20_20_1.5,kc_w_20_20_1.5,kc_mid_20_20_2.0,kc_l_20_20_2.0,kc_h_20_20_2.0,kc_w_20_20_2.0,obv,obv_roll_3,obv_roll_7,obv_roll_21,mfi_7,mfi_14,mfi_20,cmf_7,cmf_14,cmf_20,vol_spike_3,vol_spike_7,vol_spike_14,vol_spike_28,donch_h_10,donch_l_10,donch_w_10,donch_h_20,donch_l_20,donch_w_20,donch_h_55,donch_l_55,donch_w_55,roll_vwap_10,roll_vwap_20,roll_vwap_50,slope_close_5,slope_close_20,slope_close_50,ret_std_5,ret_std_21,ret_std_63,vwap_ohlc_close_session,vwap_dist_session,psar,psar_dist,dist_high_100,dist_low_100
2016-01-04 08:47:00,25.9500,25.9500,25.9500,25.9500,520.0,2.0,103.800000,25.955200,25.944800,0.000241,0.000241,0.0000,0.0000,0.0000,0.000000,25.93750,0.000482,25.933056,0.000653,25.926310,0.000914,25.938275,0.000452,26.147824,-0.007566,25.944217,25.940253,25.935579,25.932864,25.933197,25.987678,96.817308,90.125845,59.208009,43.243449,0.000723,0.000868,0.000868,0.001109,131.154684,224.437928,262.411348,0.009462,0.006510,0.002952,0.005934,0.003808,0.002126,-0.004585,-0.011539,0.006954,1.000000,0.888889,1.000000,0.971429,0.005205,0.000201,96.817213,3.182669,85.632759,0.003662,0.000141,87.291639,9.110761,46.159542,0.006309,0.000243,38.254340,24.700467,34.286782,0.009983,0.000385,21.487845,29.599048,51.826216,25.909948,25.943802,0.001306,25.901485,25.952265,0.001959,25.759513,26.117037,0.013784,25.932658,25.918347,25.946969,0.001104,25.932658,25.913577,25.951739,0.001472,1.666540e+05,1.661440e+05,1.650111e+05,1.476618e+05,82.617623,97.218643,98.149864,0.000000,0.000000,0.000000,1.061224,0.383610,0.225611,0.275639,25.95,25.9250,0.000963,25.95,25.915000,0.001349,26.375000,25.8750,0.019268,25.928732,25.926038,25.939678,0.006250,0.001300,-0.001818,0.000151,0.000116,0.002263,25.920139,0.001152,25.924524,0.000982,0.016474,0.002890
2016-01-04 08:48:00,25.9375,25.9375,25.9375,25.9375,800.0,1.0,103.750000,25.942675,25.932325,-0.000482,-0.000482,0.0000,0.0000,0.0000,0.000000,25.94000,-0.000096,25.934167,0.000129,25.927381,0.000390,25.929800,0.000297,26.143699,-0.007887,25.940859,25.939335,25.935963,25.933526,25.933588,25.985710,43.992282,56.847801,48.713022,39.222311,0.000000,0.000482,0.000386,0.000868,13.625304,65.554010,105.555556,0.005605,0.006148,-0.000543,0.004901,0.004173,0.000728,-0.003918,-0.010015,0.006097,0.777778,0.925926,0.835165,0.945055,0.007637,0.000294,43.992261,56.007686,61.093650,0.004924,0.000190,55.635866,42.071181,41.548609,0.006751,0.000260,33.195038,34.659154,31.991850,0.010103,0.000390,20.221922,33.746611,50.551650,25.911392,25.944608,0.001281,25.903088,25.952912,0.001922,25.798057,26.061543,0.010161,25.933119,25.918586,25.947652,0.001121,25.933119,25.913742,25.952496,0.001494,1.658540e+05,1.662140e+05,1.656254e+05,1.494860e+05,61.297444,90.537724,94.646014,0.000000,0.000000,0.000000,1.325967,0.835821,0.366348,0.429159,25.95,25.9250,0.000964,25.95,25.916389,0.001296,26.368333,25.8750,0.019020,25.929386,25.926375,25.932053,0.002500,0.001264,-0.000783,0.000323,0.000152,0.002263,25.920196,0.000668,25.928600,0.000343,0.016964,0.002410
2016-01-04 08:49:00,25.9275,25.9500,25.9125,25.9250,15312.0,16.0,103.703726,25.930175,25.919825,-0.000482,-0.000482,-0.0025,0.0225,0.0125,0.001446,25.93875,-0.000530,25.933889,-0.000343,25.927857,-0.000110,25.921000,0.000154,26.139450,-0.008204,25.932929,25.934557,25.933771,25.932308,25.932808,25.983329,24.192542,39.732044,40.904675,35.733383,-0.000723,-0.000241,-0.000096,0.000386,-70.886076,-29.654404,6.136951,-0.000460,0.003505,-0.003965,0.002283,0.003543,-0.001260,-0.004347,-0.008881,0.004534,0.555556,0.777778,0.612943,0.816036,0.017591,0.000679,12.731936,63.581818,62.939986,0.009578,0.000369,24.517256,55.828086,41.180281,0.008947,0.000345,23.257500,44.241185,31.927257,0.011408,0.000440,17.056603,38.899558,50.003278,25.912622,25.944240,0.001219,25.904717,25.952144,0.001829,25.877454,25.964546,0.003360,25.932346,25.915727,25.948965,0.001282,25.932346,25.910188,25.954504,0.001709,1.505420e+05,1.610167e+05,1.635380e+05,1.505620e+05,10.323514,34.348110,55.348130,-0.277211,-0.118591,-0.093019,2.761905,5.821421,4.980823,6.474940,25.95,25.9125,0.001446,25.95,25.912500,0.001446,26.365000,25.8750,0.018901,25.927315,25.926128,25.920477,-0.003125,0.001038,0.000271,0.000396,0.000190,0.002263,25.920477,0.000174,25.950000,-0.000964,0.017454,0.001929
2016-01-04 08:50:00,25.9000,25.9250,25.9000,25.9250,3436.0,5.0,103.625000,25.930175,25.919825,0.000000,0.000000,0.0250,0.0000,0.0000,0.000964,25.93625,-0.000434,25.933611,-0.000332,25.928267,-0.000126,25.921500,0.000135,26.135200,-0.008043,25.928965,25.931371,25.932017,25.931264,25.932098,25.981042,24.192542,39.732044,40.904675,35.733383,-0.000963,-0.000482,-0.000096,0.000332,-152.280702,-152.214765,-137.764933,-0.002900,0.000943,-0.003843,0.000587,0.002557,-0.001971,-0.004635,-0.008032,0.003397,0.388889,0.574074,0.446276,0.631461,0.020061,0.000774,7.443022,57.939858,67.704159,0.011781,0.000454,17.084819,54.061294,42.722039,0.010094,0.000389,19.143063,45.259965,32.543331,0.012055,0.000465,15.372259,39.995729,49.739903,25.913657,25.943926,0.001167,25.906090,25.951494,0.001751,25.878357,25.964643,0.003329,25.931646,25.913983,25.949309,0.001362,25.931646,25.908096,25.955197,0.001816,1.539780e+05,1.567913e+05,1.619986e+05,1.517659e+05,8.862934,21.443064,49.266116,-0.077769,-0.038540,-0.029157,0.527317,1.121410,1.111460,1.404633,25.95,25.9000,0.001929,25.95,25.900000,0.001929,26.365000,25.8750,0.018901,25.927018,25.926220,25.927886,-0.006250,0.000821,0.000229,0.000365,0.000190,0.002263,25.920536,0.000172,25.950000,-0.000964,0.017454,0.001929
2016-01-04 08:51:00,25.9125,25.9125,25.8975,25.8975,2052.0,2.0,103.638304,25.902675,25.892325,-0.001061,-0.001061,-0.0150,0.0000,0.0000,0.000579,25.92700,-0.001138,25.930278,-0.001264,25.927302,-0.001149,25.920800,-0.000899,26.130675,-0.008923,25.913232,25.920081,25.925113,25.926441,25.928953,25.977766,7.494913,20.894353,29.031332,29.391936,-0.001542,-0.001783,-0.001157,-0.000782,-148.823791,-235.158287,-268.617021,-0.012384,-0.004388,-0.007996,-0.004404,0.000237,-0.004641,-0.007001,-0.007826,0.000825,0.277778,0.407407,0.277778,0.445665,0.022540,0.000870,4.416126,38.074180,71.540602,0.014027,0.000542,12.299695,41.465968,44.368466,0.011337,0.000438,15.826365,38.993369,33.237403,0.012790,0.000494,13.798455,36.831709,49.537676,25.907667,25.947750,0.001546,25.897646,25.957771,0.002319,25.877260,25.964340,0.003359,25.928394,25.909552,25.947236,0.001453,25.928394,25.903271,25.953517,0.001938,1.519260e+05,1.521487e+05,1.601046e+05,1.528198e+05,6.376296,7.954353,44.896598,-0.161248,-0.089021,-0.064347,0.295962,0.622627,0.687470,0.826430,25.95,25.8975,0.002027,25.95,25.897500,0.002027,26.365000,25.8750,0.018921,25.924753,25.925378,25.925994,-0.011750,0.000222,0.000199,0.000503,0.000302,0.002264,25.920359,-0.000882,25.950000,-0.002027,0.018535,0.000869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-13 15:41:00,252.1700,252.1800,252.0400,252.1000,54024.0,1008.0,252.132389,252.150400,252.049600,-0.000159,-0.000159,-0.0700,0.0100,0.0600,0.000555,252.30520,-0.000813,252.434567,-0.001325,252.536476,-0.001728,252.445388,-0.001368,252.923510,-0.003256,252.176567,252.261092,252.370561,252.425351,252.470332,252.590439,12.622393,28.606824,38.235975,41.248223,-0.001410,-0.002177,-0.003203,-0.000951,-106.685903,-155.563753,-184.856445,-0.211417,-0.161127,-0.050290,-0.129695,-0.073567,-0.056128,-0.070270,-0.005881,-0.064389,0.066709,0.175355,0.046814,0.149842,0.196943,0.000781,4.204039,47.437070,69.919463,0.219338,0.000870,11.600737,38.305398,36.480649,0.217545,0.000863,16.032086,30.913769,18.642164,0.218076,0.000865,17.459665,27.938670,13.688595,252.092458,252.984142,0.003531,251.869537,253.207063,0.005296,251.909431,252.981345,0.004246,252.466828,252.140006,252.793649,0.002589,252.466828,252.031065,252.902590,0.003452,1.693196e+10,1.693202e+10,1.693211e+10,1.693217e+10,31.846948,53.064272,49.184226,-0.087712,0.020314,-0.024810,0.915335,0.846817,0.900907,1.157942,252.97,252.0400,0.003689,252.97,252.040000,0.003689,252.970000,251.8500,0.004443,252.476109,252.541633,252.424332,-0.137600,-0.014864,0.006584,0.000400,0.000620,0.000654,254.223349,-0.008352,252.836894,-0.002923,0.009123,0.000992
2026-03-13 15:42:00,252.0850,252.1800,252.0402,252.1000,89398.0,1339.0,252.109872,252.150400,252.049600,0.000000,0.000000,0.0150,0.0800,0.0448,0.000555,252.19920,-0.000393,252.350678,-0.000993,252.517429,-0.001653,252.447188,-0.001375,252.906710,-0.003190,252.138283,252.207394,252.316449,252.378872,252.436666,252.571206,12.622393,28.606824,38.235975,41.248223,-0.000397,-0.002098,-0.002887,-0.001584,-76.843162,-122.817289,-152.698643,-0.197339,-0.175612,-0.021728,-0.139118,-0.095417,-0.043701,-0.090188,-0.022743,-0.067445,0.090518,0.103946,0.061950,0.077028,0.177895,0.000706,3.102782,35.010826,74.519058,0.207976,0.000825,10.486745,34.627018,38.913382,0.211992,0.000841,15.276908,29.457602,19.574843,0.214348,0.000850,16.917410,27.070962,14.135917,252.029469,252.995631,0.003826,251.787928,253.237172,0.005739,251.916514,252.977862,0.004204,252.431892,252.110926,252.752857,0.002543,252.431892,252.003938,252.859846,0.003391,1.693205e+10,1.693201e+10,1.693209e+10,1.693216e+10,52.596659,53.417348,52.052130,-0.094899,-0.041933,-0.054301,1.300290,1.421311,1.479240,1.838797,252.97,252.0400,0.003689,252.97,252.040000,0.003689,252.970000,251.8500,0.004443,252.394634,252.504578,252.425987,-0.081200,-0.019915,0.004705,0.000419,0.000601,0.000654,254.208979,-0.008296,252.773143,-0.002670,0.009123,0.000992
2026-03-13 15:43:00,252.1000,252.1000,251.8900,251.9301,99873.0,2114.0,251.998252,251.980500,251.879700,-0.000674,-0.000674,-0.1699,0.0000,0.0401,0.000834,252.09402,-0.000650,252.288467,-0.001420,252.484814,-0.002197,252.445890,-0.002043,252.888011,-0.003788,252.034192,252.114963,252.239179,252.314762,252.390614,252.546065,5.783080,22.691742,34.417679,38.515401,-0.000832,-0.002083,-0.003658,-0.002711,-98.942547,-128.963367,-164.999632,-0.227700,-0.196447,-0.031253,-0.163480,-0.118105,-0.045375,-0.118319,-0.041858,-0.076461,0.087935,0.081721,0.055387,0.054717,0.188597,0.000749,1.951146,48.563071,80.437660,0.208265,0.000827,8.976157,39.941903,42.397364,0.211850,0.000841,14.195229,32.436094,20.970725,0.214141,0.000850,16.127398,29.146827,14.832151,251.936621,253.026989,0.004319,251.664029,253.299581,0.006478,251.910502,252.981278,0.004242,252.384102,252.063435,252.704769,0.002541,252.384102,251.956546,252.811658,0.003388,1.693195e+10,1.693199e+10,1.693205e+10,1.693215e+10,32.113729,50.073992,48.698549,-0.351535,-0.111657,-0.088212,1.231505,1.537924,1.548734,1.954208,252.84,251.8900,0.003771,252.97,251.890000,0.004287,252.970000,251.8500,0.004446,252.284398,252.455777,252.416226,-0.057980,-0.027723,0.002381,0.000417,0.000601,0.000658,254.191880,-0.008898,252.714491,-0.003114,0.009804,0.000318
2026-03-13 15:44:00,251.9150,251.9300,251.6598,251.7199,79542.0,2049.0,251.769574,251.770200,251.669600,-0.000834,-0.000835,-0.1951,0.0150,0.0601,0.001073,251.99800,-0.001104,252.214011,-0.001959,252.445524,-0.002874,252.439888,-0.002852,252.867310,-0.004538,251.877046,251.983275,252.135323,252.229782,252.329640,252.513666,2.883546,17.475970,30.376081,35.463204,-0.001508,-0.001904,-0.003050,-0.003267,-151.481366,-145.794331,-185.019790,-0.286302,-0.232389,-0.053913,-0.201752,-0.145987,-0.055765,-0.155778,-0.064642,-0.091137,0.092160,0.090204,0.049172,0.055503,0.215831,0.000857,1.136628,63.842612,85.792295,0.217127,0.000863,7.379820,47.984399,46.817859,0.216025,0.000858,12.926536,37.148688,22.927926,0.216816,0.000861,15.169982,32.472369,15.855250,251.804126,253.079484,0.005052,251.485286,253.398324,0.007578,251.879396,253.000380,0.004441,252.320845,251.995938,252.645751,0.002575,252.320845,251.887636,252.754053,0.003434,1.693187e+10,1.693196e+10,1.693201e+10,1.693213e+10,18.720423,43.879615,47.057218,-0.453348,-0.173323,-0.104269,0.887703,1.165817,1.178674,1.524016,252.71,251.6598,0.004172,252.97,251.659800,0.005205,252.970000,251.6598,0.005205,252.208205,252.406482,252.404876,-0.101010,-0.038006,-0.000370,0.000356,0.000620,0.000658,254.177195,-0.009668,252.632042,-0.003624,0.010647,0.000239
2026-03-13 15:45:00,251.7100,251.7500,251.6400,251.6800,55962.0,1259.0,251.697268,251.730300,251.629700,-0.000159,-0.000159,-0.0300,0.0400,0.0400,0.000437,251.90600,-0.000897,252.106222,-0.001691,252.405529,-0.002874,252.435288,-0.002992,252.847810,-0.004619,251.778523,251.882184,252.044259,252.151242,252.270582,252.480973,2.523322,16.629491,29.664005,34.911788,-0.001666,-0.001824,-0.002813,-0.003326,-124.842875,-136.243231,-168.319812,-0.296943,-0.258211,-0.038733,-0.222649,-0.171541,-0.051108,-0.186535,-0.089020,-0.097514,0.083518,0.087871,0.037692,0.047417,0.180554,0.000717,0.905803,54.532960,89.438943,0.201823,0.000802,6.805215,45.649764,50.708611,0.208452,0.000828,12.439297,36.426919,24.796528,0.211729,0.000841,14.794683,32.114328,16.858419,251.686659,253.124951,0.005698,251.327086,253.484524,0.008547,251.854084,253.016492,0.004605,252.259812,251.942901,252.576723,0.002513,252.259812,251.837264,252.682360,0.003350,1.693182e+10,1.693188e+10,1.693197e+10,1.693211e+10,17.821182,37.258323,46.086107,-0.430128,-0.262705,-0.092734,0.713264,0.780599,0.838553,1.050626,252.71,251.6400,0.004251,252.97,251.640000,0.005284,252.970000,251.6400,0.005284,252.138711,252.374435,252.398549,-0.122010,-0.049549,-0.003456,0.000365,0.000620,0.000654,254.166801,-0.009784,252.515373,-0.003319,0.010807,0.000159

In [3]:
# --- DIAGNOSTICS & FLAGGING ---
# Identifies DRIFT, CONST, or HIGH_NA features for special handling.
df_inds_flag, diag = feats.flag_indicators(
    df = df_inds_unsc,
    train_prop = params.train_prop,
    pct_shift_thresh = 0.16,
    frac_outside_thresh = 0.06,
    min_train_samples = 50,
    na_rate_thresh = 0.4,
    const_tol = 1e-12,
)

# Display diagnostic summary
display(diag.sort_values("status", ascending=False).head(10))

Flagging indicators:   0%|          | 0/130 [00:00<?, ?feat/s]

,feature,status,reason,pct_shift_val,pct_shift_te,frac_val_out,frac_te_out,na_rate_train,na_rate_all
4,volume,OK,,0.009137,0.010172,0.042845,0.054326,0.0,0.0
5,trade_count,OK,,0.013069,0.010890,0.024688,0.016161,0.0,0.0
9,ret,OK,,0.000000,0.000000,0.011721,0.018990,0.0,0.0
10,log_ret,OK,,0.000000,0.000000,0.011721,0.018990,0.0,0.0
12,upper_shad,OK,,0.000000,0.000000,0.017721,0.041656,0.0,0.0
13,lower_shad,OK,,0.000000,0.000000,0.019401,0.043891,0.0,0.0
14,range_pct,OK,,0.055228,0.014177,0.006858,0.011353,0.0,0.0
16,sma_pct_5,OK,,0.003075,0.000214,0.011547,0.018468,0.0,0.0
18,sma_pct_9,OK,,0.000525,0.008644,0.010982,0.018608,0.0,0.0
20,sma_pct_21,OK,,0.002549,0.013939,0.010358,0.018993,0.0,0.0

In [4]:
# --- APPLY ROBUST Z (RZ) TO DRIFTS ---
# Preserve raw prices for plotting/strategy verification later
df_inds_flag[[f"{c}_raw" for c in params.strategy_cols_tick]] = df_inds_unsc[params.strategy_cols_tick]
df_inds_flag["close_raw"] = df_inds_unsc["close"]

# Apply the RZ transformation specifically to flagged columns
df_inds_rz = feats.apply_rz_to_drifts(
    df = df_inds_flag,
    diag = diag,
    rz_window = 60,
    eps = 1e-6
)

df_inds_rz

Applying RZ to DRIFTs:   0%|          | 0/62 [00:00<?, ?feat/s]

,volume,trade_count,ret,log_ret,upper_shad,lower_shad,range_pct,sma_pct_5,sma_pct_9,sma_pct_21,sma_pct_50,sma_pct_100,rsi_3,rsi_7,rsi_14,rsi_21,roc_3,roc_5,roc_10,roc_21,cci_7,cci_14,cci_20,stoch_k_5_3_3,stoch_d_5_3_3,stoch_k_14_3_3,stoch_d_14_3_3,atr_pct_3,plus_di_3,minus_di_3,adx_3,atr_pct_7,plus_di_7,minus_di_7,adx_7,atr_pct_14,plus_di_14,minus_di_14,adx_14,atr_pct_21,plus_di_21,minus_di_21,adx_21,bb_w_20_2p0,bb_w_20_3p0,bb_w_50_2p0,kc_w_20_20_1.5,kc_w_20_20_2.0,mfi_7,mfi_14,mfi_20,cmf_7,cmf_14,cmf_20,vol_spike_3,vol_spike_7,vol_spike_14,vol_spike_28,donch_w_10,donch_w_20,donch_w_55,ret_std_5,ret_std_21,ret_std_63,vwap_dist_session,psar_dist,dist_high_100,dist_low_100,atr_21_raw,adx_21_raw,rsi_21_raw,vwap_ohlc_close_session_raw,close_raw,open_RZ,high_RZ,low_RZ,close_RZ,vwap_RZ,ask_RZ,bid_RZ,body_RZ,sma_5_RZ,sma_9_RZ,sma_21_RZ,sma_50_RZ,sma_100_RZ,ema_3_RZ,ema_5_RZ,ema_9_RZ,ema_13_RZ,ema_21_RZ,ema_50_RZ,macd_line_3_10_4_RZ,macd_signal_3_10_4_RZ,macd_diff_3_10_4_RZ,macd_line_6_13_5_RZ,macd_signal_6_13_5_RZ,macd_diff_6_13_5_RZ,macd_line_12_26_9_RZ,macd_signal_12_26_9_RZ,macd_diff_12_26_9_RZ,atr_3_RZ,atr_7_RZ,atr_14_RZ,atr_21_RZ,bb_lband_20_2p0_RZ,bb_hband_20_2p0_RZ,bb_lband_20_3p0_RZ,bb_hband_20_3p0_RZ,bb_lband_50_2p0_RZ,bb_hband_50_2p0_RZ,kc_mid_20_20_1.5_RZ,kc_l_20_20_1.5_RZ,kc_h_20_20_1.5_RZ,kc_mid_20_20_2.0_RZ,kc_l_20_20_2.0_RZ,kc_h_20_20_2.0_RZ,obv_RZ,obv_roll_3_RZ,obv_roll_7_RZ,obv_roll_21_RZ,donch_h_10_RZ,donch_l_10_RZ,donch_h_20_RZ,donch_l_20_RZ,donch_h_55_RZ,donch_l_55_RZ,roll_vwap_10_RZ,roll_vwap_20_RZ,roll_vwap_50_RZ,slope_close_5_RZ,slope_close_20_RZ,slope_close_50_RZ,vwap_ohlc_close_session_RZ,psar_RZ
2016-01-04 08:47:00,520.0,2.0,0.000241,0.000241,0.0000,0.0000,0.000000,0.000482,0.000653,0.000914,0.000452,-0.007566,96.817308,90.125845,59.208009,43.243449,0.000723,0.000868,0.000868,0.001109,131.154684,224.437928,262.411348,1.000000,0.888889,1.000000,0.971429,0.000201,96.817213,3.182669,85.632759,0.000141,87.291639,9.110761,46.159542,0.000243,38.254340,24.700467,34.286782,0.000385,21.487845,29.599048,51.826216,0.001306,0.001959,0.013784,0.001104,0.001472,82.617623,97.218643,98.149864,0.000000,0.000000,0.000000,1.061224,0.383610,0.225611,0.275639,0.000963,0.001349,0.019268,0.000151,0.000116,0.002263,0.001152,0.000982,0.016474,0.002890,0.009983,51.826216,43.243449,25.920139,25.9500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2016-01-04 08:48:00,800.0,1.0,-0.000482,-0.000482,0.0000,0.0000,0.000000,-0.000096,0.000129,0.000390,0.000297,-0.007887,43.992282,56.847801,48.713022,39.222311,0.000000,0.000482,0.000386,0.000868,13.625304,65.554010,105.555556,0.777778,0.925926,0.835165,0.945055,0.000294,43.992261,56.007686,61.093650,0.000190,55.635866,42.071181,41.548609,0.000260,33.195038,34.659154,31.991850,0.000390,20.221922,33.746611,50.551650,0.001281,0.001922,0.010161,0.001121,0.001494,61.297444,90.537724,94.646014,0.000000,0.000000,0.000000,1.325967,0.835821,0.366348,0.429159,0.000964,0.001296,0.019020,0.000323,0.000152,0.002263,0.000668,0.000343,0.016964,0.002410,0.010103,50.551650,39.222311,25.920196,25.9375,-2.000000,-2.000000,-2.000000,-2.000000,0.000000,-2.000000,-2.000000,0.000000,2.000000,2.000000,2.000000,-2.000000,-2.000000,-2.000000,-2.000000,2.000000,2.000000,2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,2.000000,-2.000000,2.000000,2.000000,-2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,-2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,-2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,2.000000,-2.000000,0.000000,2.000000,2.000000,2.000000,-2.000000,-2.000000,2.000000,2.000000,2.000000
2016-01-04 08:49:00,15312.0,16.0,-0.000482,-0.000482,0.0225,0.0125,0.001446,-0.000530,-0.000343,-0.000110,0.000154,-0.008204,24.192542,39.732044,40.904675,35.733383,-0.000723,-0.000241,-0.000096,0.000386,-70.886076,-29.654404,6.136951,0.555556,0.777778,0.612943,0.816036,0.000679,12.731936,63.581818,62.939986,0.000369,24.517256,55.828086,41.180281,0.000345,23.257500,44.241185,31.927257,0.000440,17.056603,38.899558,50.003278,0.001219,0.001829,0.003360,0.001282,0.001709,10.323514,34.348110,55.348130,-0.277211,-0.118591,-0.093019,2.761905,5.821421,4.980823,6.474940,0.001446,0.001446,0.018901,0.000396,0.000190,0.002263,0.000174,-0.000964,0.017454,0.001929,0.011408,50.003278,35.733383,25.920477,25.9250,-1.600000,0.000000,-4.000000,-2.000000,143.722275,-1.996008,-2.004008,-2500.000000,0.000000,0.000000,1.000000,-2.076696,-2.060606,-4.721678,-10.415243,-9.415982,-1.677806,-1.992158,-2.419797,-3.144266,-14.596593,-1.957694,-5.068752,-1.459090,-2.845906,0.000000,1.487189,-3.647511,8.187303,7.371363,9.933091,21.771259,1.703507,0.000000,2.032672,-1.000000,4.119693,-3.495692,-1.353564,-21.906086,3.843081,-1.353564,-41.028793,5.304260,-38.279999,-146.495239,-4.796279,1.179701,0.000000,-12500.000000,0.000000,-3.600000,-1.000000,0.000000,1.587118,1.910762,1.000000,-3.000000,-12.666667,2.039589,2.037800,10.500000
2016-01-04 08:50:00,3436.0,5.0,0.000000,0.000000,0.0000,0.0000,0.000964,-0.000434,-0.000332,-0.000126,0.000135,-0.008043,24.192542,39.732044,40.904675,35.733383,-0.000963,-0.000482,-0.000096,0.000332,-152.280702,-152.214765,-137.764933,0.388889,0.574074,0.446276,0.631461,0.000774,7.443022,57.939858,67.704159,0.000454,17.084819,54.061294,42.722039,0.000389,19.143063,45.259965,32.543331,0.000465,15.372259,39.995729,49.739903,0.001167,0.001751,0.003329,0.001362,0.001816,8.862934,21.443064,49.266116,-0.077769,-0.038540,-0.029157,0.527317,1.121410,1.111460,1.404633,0.001929,0.001929,0.018901,0.000365,0.000190,0.002263,0.000172,-0.000964,0.017454,0.001929,0.012055,49.739903,35.733383,25.920536,25.9250,-4.000000,-6.000000,-1.600000,-1.000000,-40.257648,-0.999001,-1.001001,20.000000,-3.000000,-2.000000,1.281046,-0.989568,-2.019802,-1.650452,-2.128928,-2.657604,-2.981029,-3.091624,-2.067258,-1.478723,-2.749863,-0.971103,-1.917385,-4.993946,-1.418668,-2.000000,1.494025,-1.925998,1.719293,1.755365,1.857143,1.911843,1.691204,-2.000000,1.799541,-3.197458,1.356238,-1.271698,-3.153480,-2.229323,1.491101,-3.153480,-2.181172,1.635134,-1.873777,-2.630206,-2.556893,1.752367,0.000000,-3.000000,0.000000,-8.608696,-0.666667,0.000000,0.870676,0.984685,4.690715,-1.583333,-2.706889,0.989471,1.013931,1.680000
2016-01-04 08:51:00,2052.0,2.0,-0.001061,-0.001061,0.0000,0.0000,0.000579,-0.001138,-0.001264,-0.001149,-0.000899,-0.008923,7.494913,20.894353,29.031332,29.391936,-0.001542,-0.001783,-0.001157,-0.000782,-148.823791,-235.158287,-268.617021,0.277778,0.407407,0.277778,0.445665,0.000870,4.416126,38.074180,71.540602,0.000542,12.299695,41.465968,44.368466,0.000438,15.826365,38.993369,33.237403,0.000494,13.798455,36.831709,49.537676,0.001546,0.002319,0.003359,0.001453,0.001938,6.376296,7.954353,44.896598,-0.161248,-0.089021,-0.064347,0.295962,0.622627,0.687470,0.826430,0.002027,0.002027,0.018921,0.000503,0.000302,0.002264,-0.000882,-0.002027,0.018535,0.000869,0.012790,49.537676,29.391936,25.920359,25.8975,-1.500000,-4.000000,-1.000000,-4.400000,12.977802,-4.391218,-4.400000,-6.000000,-8.400000,-24.000000,-0.166667,-0.168675,-2.064706,-2.484064,-3.029473,-4.786986,-10.559664,-9.894438,-2.336864,-2.179106,-2.985822,-2.376433,-2.554053,-12.441536,-1.983148,-14.324183,1.000000,-2.372381,1.000000,1.000000,1.088122,1.064000,-3.029496,22.420547,-3.340286,17.020491,0.000000,-0.010909,-12.661520,-2.356972,-1.000000,-12.661520,-2.040669,0.000000,-1.000000,-1.729554,-2.330683,2.098366,0.000000,-1.200000,0.000000,-6.000000,0.000000,0.000000,3.846134,4.177996,13.579055,-1.533333,-3.608495,0.000000,4.252213,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-13 15:41:00,54024.0,1008.0,-0.000159,-0.000159,0.0100,0.0600,0.000555,-0.000813,-0.001325,-0.001728,-0.001368,-0.003256,12.622393,28.606824,38.235975,41.248223,-0.001410,-0.002177,-0.003203,-0.000951,-106.685903,-155.563753,-184.856445,0.066709,0.175355,0.046814,0.149842,0.000781,4.204039,47.437070,69.919463,0.000870,11.600737,38.305398,36.480649,0.000863,16.032086,30.913769,18.642164,0.000865,17.459665,27.938670,13.688595,0.003531,0.005296,0.004246,0.002589,0.003452,31.846948,53.064272,49.184226,-0.087712,0.020314,-0.024810,0.915335,0.846817,0.900907,1.157942,0.003689,0.003689,0.004443,0.000400,0.000620,0.000654,-0.008352,-0.002923,0.009123,0.000992,0.218076,13.688595,41.248223,254.223349,252.1000,-0.670698,-1.019880,-0.750969,-0.845640,0.528720,-0.845782,-0.845499,-0.436121,-0.441551,-0.163630,0.039259,-0.389602,-0.709949,-0.826744,-0.612253,-0.277835,-0.129387,-0.071040,-0.309319,-1.320554,-1.116168,-1.473734,-1.018644,-0.593013,-2.394698,-0.128945,0.369140,-2.051012,-0.891043,-0.428495,-0.729755,-1.071008,-0.035315,0.061757,0.005603,0.020079,0.127973,-0.877697,-0.069860,-0.046804,-0.105856,-0.069860,-0.043063,-0.120415,-1.899959,-1.385820,-0.508494,0.232016,0.087719,-0.326241,0.028470,-0.061433,-1.347735,0.000000,1.586906,1.217006,0.303012,-1.987182,-0.156311,2.289213,0.552978,0.116707
2026-03-13 15:42:00,89398.0,1339.0,0.000000,0.000000,0.0800,0.0448,0.000555,-0.000393,-0.000993,-0.001653,-0.001375,-0.003190,12.622393,28.606824,38.235975,41.248223,-0.000397,-0.002098,-0.002887,-0.001584,-76.843162,-122.817289,-152.698643,0.090518,0.103946,0.061950,0.077028,0.000706,3.102782,35.010826,74.519058,0.000825,10.486745,34.627018,38.913382,0.000841,15.276908,29.457602,19.574843,0.000850,16.917410,27.070962,14.135917,0.003826,0.005739,0.004204,0.002543,0.003391,52.596659,53.417348,52.052130,-0.094899,-0.041933,-0.054301,1.300290,1.421311,1.479240,1.838797,0.003689,0.003689,0.004443,0.000419,0.000601,0.000654,-0.008296,-0.002670,0.009123,0.000992,0.214348,14.135917,41.248223,254.208979,252.1000,-0.850018,-0.987833,-0.786276,-0.823529,0.013387,-0.823675,-0.823384,0.315789,-0.801345,-0.381974,0.013522,-0.351558,-0.689306,-0.961428,-0.905337,-0.457210,-0.213214,-0.120567,-0.310657,-1.114981,-1.214457,-0.652250,-1.087441,-0.817583,-1.865027,-0.263227,0.234742,-2.136461,-1.230513,-0.785084,-0.977991,-1.350419,-0.094619,0.078020,-0.063779,0.059449,0.137402,-0.832283,-0.122136,-0.084099,-0.169625,-0.122136,-0.082564,-0.189982,-1.030409,-1.469865,-0.613572,0.093279,0.089686,-0.528736,0.028470,-0.054008,-1.325801,0.000000,1.186582,1.066201,0.306879,-1.042141,-0.310384,2.073073,0.527587,0.019620
2026-03-13 15:43:00,99873.0,2114.0,-0.000674,-0.000674,0.0000,0.0401,0.000834,-0.000650,-0.001420,-0.002197,-0.002043,-0.003788,5.783080,22.691742,34.417679,38.515401,-0.000832,-0.002083,-0.003658,-0.002711,-98.942547,-128.963367,-164.999632,0.087935,0.081721,0.055387,0.054717,0.000749,1.951146,48.563071,80.437660,0.000827,8.976157,39.941903,42.397364,0.000841,14.195229,32.436094,20.970725,0.000850,16.127398,29.146827,14.832151,0.004319,0.006478,0.004242,0.002541,0.003388,32.113729,50.073992,48.698549,-0.351535,-0.111657,-0.088212,1.231505,1.537924,1.548734,1.954208,0.003771,0.004287,0.004446,0.000417,0.000601,0.000658,-0.008898,-0.003114,0.009804,0.000318,0.214141,14.832151,38.515401,254.191880,251.9301,-0.811585,-1.144440,-1.109248,-1.244334,1.472992,-1.244428,-1.244241,-1.630526,-1.098811,-0.571120,-0.026648,-0.322155,-0.673409,-1.264212,-1.210814,-0.738751,-0.363802,-0.200079,-0.317527,-1.349692,-1.362193,-0.943549,-1.322266,-1.042780,-1.936402,-0.452877,0.078819,-2.403354,-0.925414,-0.805211,-0.922373,-1.281883,-0.203902,0.121723,-0.193649,0.143045,0.129398,-0.789868,-0.202065,-0.158243,-0.263533,-0.202065,-0.159090,-0.282161,-2.004585,-1.670461,-0.934377,-0.026077,-0.132075,-1.218391,0.031250,-0.404651,-1.303867,0.000000,1.480914,1.484831,0.697704,-0.671057,-0.548595,1.785584,1.120344,-0.056744
2026-03-13 15:44:00,79542.0,2049.0,-0.000834,-0.000835,0.0150,0.0601,0.001073,-0.001104,-0.001959,-0.002874,-0.002852,-0.004538,2.883546,17.475970,30.376081,35.463204,-0.001508,-0.001904,-0.003050,-0.003267,-151.481366,-145.794331,-185.019790,0.092160,0.090204,0.049172,0.055503,0.000857,1.136628,63.842612,85.792295,0.000863,7.379820,47.984399,46.817859,0.000858,12.926536,37.148688,22.927926,0.000861,15.169982,32.472369,15.855250,0.005052,0.007578,0.004441,0.002575,0.003434,18.720423,43.879615,47.057218,-0.453348,-0.173323,-0.104269,0.887703,1.165817,1.178674,1.524016,0.004172,0.005205,0.005205,0.000356,0.000620,0.000658,-0.009668,-0.003624,0.010647,0.000239,0.216816,15.855250,35.463204,254.177195,251.7199,-1.262805,-1.554030,-1.703083,-1.764954,0.974168,-1.765230,-1.764677,-1.771165,-1.366993,-0.803252,-0.082663,-0.305782,-0.666101,-1.705398,-1.641729,-1.060019,-0.641966,-0.316323,-0.342177,-1.802736,-1.668613,-1.622127,-1.691159,-1.304592,-2.379207,-0.705419,-0.090666,-2.837797,-0.155014,-0.439738,-0.657333,-1.053019,-0.489969,0.194552,-0.598252,0.273842,0.087986,-0.735376,-0.331057,-0.291557,-0.387860,-0.331057,-0.291416,-0.406668,-2.780449,-1.950421,-1.281959,-0.148929,-0.394089,-2.276782,0.033755,-0.990154,-1.303867,-0.481519,2.141794,2.041799,1.174815,-1.411932,-0.862296,1.445620,1.879701,-0.157541
2026-03-13 15:45:00,55962.0,1259.0,-0.000159,-0.000159,0.0400,0.0400,0.000437,-0.000897,-0.001691,-0.002874,-0.002992,-0.004619,2.523322,16.629491,29.664005,34.911788,-0.001666,-0.001824,-0.002813,-0.003326,-124.842875,-136.243231,-168.319812,0.083518,0.087871,0.037692,0.047417,0.000717,0.905803,54.532960,89.438943,0.000802,6.805215,45.649764,50.708611,0.000828,12.439297,36.426919,24.796528,0.000841,14.794683,32.114328,16.858419,0.005698,0.008547,0.004605,0.002513,0.003350,17.821182,37.258323,46.086107,-0.430128,-0.262705,-0.092734,0.713264,0.780599,0.838553,1.050626,0.004251,0.005284,0.005284,0.000365,0.000620,0.000654,-0.009784,-0.003319,0.010807,0.000159,0.211729,16.858419,34.911788,254.166801,251.6800,-1.762805,-1.915432,-1.690313,-1.839009,0.156077,-1.839277,-1.838742,0.025654,-1.620242,-1.101028,-0.146648,-0.286042,-0.659291,-1.973956,-1.968486,-1.328322,-0.917439,-0.439812,-0.373118,-1.885004,-1.888755,-1.156787,-1.892580,-1.531884,-2.180720,-0.912769,-0.272012,-3.026601,-0.903549,-0.843145,-0.970348,-1.393057,-0.886899,0.257629,-1.075107,0.388025,0.054287,-0.686126,-0.463672,-0.415091,-0.529030,-0.463672,-0.413059,-0.557963,-3.326310,-2.682461,-1.657736,-0.279534,-0.404040,-2.367816,0.034632,-1.009846,-1.276243,-0.545455,1.996525,2.028445,1.226805,-1.773502,-1.175512,1.121974,1.994721,-0.313916

In [5]:
# --- MIN-MAX SCALING & TIME FEATURES ---
# Scale all features (including RZ) to [0,1] based on training distribution
df_feat_scal, stats = feats.scale_features(
    df=df_inds_rz,
    train_prop=params.train_prop,
    p_lo=1.0,
    p_hi=99.0,
    include_rz=True
)
stats

MinMax Scaling:   0%|          | 0/130 [00:00<?, ?feat/s]

                                   min           max
feature
volume                      257.000000  1.117148e+06
trade_count                   1.000000  3.982000e+03
ret                          -0.001771  1.767095e-03
log_ret                      -0.001773  1.765535e-03
upper_shad                    0.000000  1.300000e-01
...                                ...           ...
slope_close_5_RZ             -8.776007  9.000000e+00
slope_close_20_RZ            -8.342307  8.807574e+00
slope_close_50_RZ            -8.137803  8.468831e+00
vwap_ohlc_close_session_RZ   -8.176345  9.615751e+00
psar_RZ                      -7.248172  7.627203e+00

[130 rows x 2 columns]

In [6]:
df_time = feats.add_session_centered_time_features(df_feat_scal)
df_time

,time_minute,time_hour,time_dow,time_month,time_day_of_year,time_week_of_year,time_in_sess,time_premark,time_afthour
2016-01-04 08:47:00,0.303472,0.270833,0.500000,0.500000,0.508219,0.500000,0.0,1.0,0.0
2016-01-04 08:48:00,0.304167,0.270833,0.500000,0.500000,0.508219,0.500000,0.0,1.0,0.0
2016-01-04 08:49:00,0.304861,0.270833,0.500000,0.500000,0.508219,0.500000,0.0,1.0,0.0
2016-01-04 08:50:00,0.305556,0.270833,0.500000,0.500000,0.508219,0.500000,0.0,1.0,0.0
2016-01-04 08:51:00,0.306250,0.270833,0.500000,0.500000,0.508219,0.500000,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
2026-03-13 15:41:00,0.590972,0.562500,0.071429,0.666667,0.694521,0.692308,1.0,0.0,0.0
2026-03-13 15:42:00,0.591667,0.562500,0.071429,0.666667,0.694521,0.692308,1.0,0.0,0.0
2026-03-13 15:43:00,0.592361,0.562500,0.071429,0.666667,0.694521,0.692308,1.0,0.0,0.0
2026-03-13 15:44:00,0.593056,0.562500,0.071429,0.666667,0.694521,0.692308,1.0,0.0,0.0
2026-03-13 15:45:00,0.593750,0.562500,0.071429,0.666667,0.694521,0.692308,1.0,0.0,0.0

In [7]:
df_feat_scal = pd.concat([df_feat_scal, df_time], axis=1)
df_feat_scal

,volume,trade_count,ret,log_ret,upper_shad,lower_shad,range_pct,sma_pct_5,sma_pct_9,sma_pct_21,sma_pct_50,sma_pct_100,rsi_3,rsi_7,rsi_14,rsi_21,roc_3,roc_5,roc_10,roc_21,cci_7,cci_14,cci_20,stoch_k_5_3_3,stoch_d_5_3_3,stoch_k_14_3_3,stoch_d_14_3_3,atr_pct_3,plus_di_3,minus_di_3,adx_3,atr_pct_7,plus_di_7,minus_di_7,adx_7,atr_pct_14,plus_di_14,minus_di_14,adx_14,atr_pct_21,plus_di_21,minus_di_21,adx_21,bb_w_20_2p0,bb_w_20_3p0,bb_w_50_2p0,kc_w_20_20_1.5,kc_w_20_20_2.0,mfi_7,mfi_14,mfi_20,cmf_7,cmf_14,cmf_20,vol_spike_3,vol_spike_7,vol_spike_14,vol_spike_28,donch_w_10,donch_w_20,donch_w_55,ret_std_5,ret_std_21,ret_std_63,vwap_dist_session,psar_dist,dist_high_100,dist_low_100,atr_21_raw,adx_21_raw,rsi_21_raw,vwap_ohlc_close_session_raw,close_raw,open_RZ,high_RZ,low_RZ,close_RZ,vwap_RZ,ask_RZ,bid_RZ,body_RZ,sma_5_RZ,sma_9_RZ,sma_21_RZ,sma_50_RZ,sma_100_RZ,ema_3_RZ,ema_5_RZ,ema_9_RZ,ema_13_RZ,ema_21_RZ,ema_50_RZ,macd_line_3_10_4_RZ,macd_signal_3_10_4_RZ,macd_diff_3_10_4_RZ,macd_line_6_13_5_RZ,macd_signal_6_13_5_RZ,macd_diff_6_13_5_RZ,macd_line_12_26_9_RZ,macd_signal_12_26_9_RZ,macd_diff_12_26_9_RZ,atr_3_RZ,atr_7_RZ,atr_14_RZ,atr_21_RZ,bb_lband_20_2p0_RZ,bb_hband_20_2p0_RZ,bb_lband_20_3p0_RZ,bb_hband_20_3p0_RZ,bb_lband_50_2p0_RZ,bb_hband_50_2p0_RZ,kc_mid_20_20_1.5_RZ,kc_l_20_20_1.5_RZ,kc_h_20_20_1.5_RZ,kc_mid_20_20_2.0_RZ,kc_l_20_20_2.0_RZ,kc_h_20_20_2.0_RZ,obv_RZ,obv_roll_3_RZ,obv_roll_7_RZ,obv_roll_21_RZ,donch_h_10_RZ,donch_l_10_RZ,donch_h_20_RZ,donch_l_20_RZ,donch_h_55_RZ,donch_l_55_RZ,roll_vwap_10_RZ,roll_vwap_20_RZ,roll_vwap_50_RZ,slope_close_5_RZ,slope_close_20_RZ,slope_close_50_RZ,vwap_ohlc_close_session_RZ,psar_RZ,time_minute,time_hour,time_dow,time_month,time_day_of_year,time_week_of_year,time_in_sess,time_premark,time_afthour
2016-01-04 08:47:00,0.000235,0.000251,0.568673,0.569106,0.000000,0.000000,0.000000,0.625118,0.617515,0.604468,0.537265,0.145141,0.968173,0.903736,0.592269,0.385027,0.617371,0.608483,0.577922,0.569920,0.827744,0.969336,1.000000,1.000000,0.888889,1.000000,0.971429,0.062041,0.968304,0.031838,0.821628,0.044863,0.914523,0.096586,0.380528,0.083018,0.457397,0.303614,0.321154,0.137632,0.248309,0.398007,0.674196,0.075003,0.075003,0.541332,0.131051,0.131051,0.826176,0.972186,0.981499,0.500000,0.500130,0.500653,0.404908,0.091412,0.043448,0.046360,0.077947,0.074984,0.717843,0.068029,0.053566,1.000000,0.547688,0.573531,0.696254,0.126473,0.009983,51.826216,43.243449,25.920139,25.9500,0.470169,0.448904,0.498787,0.471218,0.494730,0.471126,0.471200,0.500000,0.473684,0.477012,0.479256,0.475462,0.490903,0.472149,0.473562,0.474042,0.475296,0.478562,0.487237,0.488860,0.486769,0.497824,0.484518,0.482683,0.493139,0.486335,0.489646,0.487147,0.127322,0.150441,0.170387,0.181595,0.621238,0.343150,0.693088,0.271876,0.660979,0.296382,0.478818,0.526104,0.423193,0.478818,0.545772,0.409447,0.324983,0.327751,0.333903,0.350406,0.419916,0.541399,0.492341,0.467980,0.814815,0.071429,0.512665,0.515093,0.509213,0.493700,0.486435,0.490033,0.459549,0.487260,0.303472,0.270833,0.500000,0.500000,0.508219,0.500000,0.0,1.0,0.0
2016-01-04 08:48:00,0.000486,0.000000,0.364453,0.364863,0.000000,0.000000,0.000000,0.475912,0.523860,0.546369,0.526550,0.129635,0.439922,0.566988,0.470745,0.330657,0.499336,0.559746,0.534687,0.555082,0.534795,0.637187,0.707205,0.777778,0.925926,0.835165,0.945055,0.092263,0.439982,0.560283,0.516970,0.061801,0.581985,0.450114,0.326947,0.089338,0.392552,0.435853,0.291600,0.139458,0.229490,0.462517,0.654800,0.073428,0.073428,0.395104,0.133209,0.133209,0.612974,0.905377,0.946460,0.500000,0.500130,0.500653,0.514395,0.207041,0.071745,0.072578,0.077987,0.071710,0.708411,0.145706,0.070576,1.000000,0.532295,0.525210,0.716958,0.105445,0.010103,50.551650,39.222311,25.920196,25.9375,0.362702,0.342411,0.391586,0.362939,0.494730,0.362871,0.362916,0.500000,0.577624,0.578523,0.579670,0.351758,0.335298,0.367206,0.369981,0.575802,0.576547,0.581231,0.374751,0.364881,0.364365,0.383810,0.361090,0.603349,0.365042,0.605703,0.604874,0.343298,0.210770,0.236529,0.259786,0.272996,0.708903,0.425868,0.782346,0.354642,0.739614,0.224102,0.581211,0.632543,0.525891,0.581211,0.653035,0.512980,0.305553,0.347610,0.355010,0.376983,0.419916,0.541399,0.492341,0.517241,0.814800,0.071429,0.632941,0.641759,0.652213,0.381188,0.369816,0.610467,0.571959,0.621710,0.304167,0.270833,0.500000,0.500000,0.508219,0.500000,0.0,1.0,0.0
2016-01-04 08:49:00,0.013479,0.003768,0.364387,0.364797,0.173077,0.096154,0.414185,0.364009,0.439766,0.490821,0.516694,0.114353,0.241924,0.393790,0.380330,0.283484,0.381358,0.468353,0.491451,0.525374,0.324144,0.438152,0.511257,0.555556,0.777778,0.612943,0.816036,0.215957,0.127336,0.636053,0.539893,0.124204,0.255090,0.597668,0.322666,0.120578,0.265182,0.563090,0.290768,0.158648,0.182435,0.542664,0.646455,0.069485,0.069485,0.120524,0.153517,0.153517,0.103235,0.343481,0.553481,0.361395,0.439257,0.450816,1.000000,1.000000,0.999515,1.000000,0.119594,0.081034,0.703865,0.178474,0.088237,1.000000,0.516627,0.426281,0.737681,0.084397,0.011408,50.003278,35.733383,25.920477,25.9250,0.384195,0.448904,0.284385,0.362939,0.767857,0.363087,0.362699,0.400000,0.473684,0.477012,0.529463,0.347014,0.330582,0.224394,0.000000,0.000000,0.390356,0.376296,0.351141,0.293948,0.000000,0.386222,0.171704,0.394651,0.310862,0.486335,0.575329,0.224802,0.468930,0.467733,0.614394,1.000000,0.695907,0.343150,0.783804,0.230493,0.822955,0.170047,0.409520,0.000000,0.620530,0.409520,0.000000,0.684029,0.000000,0.000000,0.283286,0.366082,0.419916,0.000000,0.492341,0.379310,0.814807,0.071429,0.608111,0.636107,0.580713,0.324933,0.000000,0.612851,0.574083,1.000000,0.304861,0.270833,0.500000,0.500000,0.508219,0.500000,0.0,1.0,0.0
2016-01-04 08:50:00,0.002846,0.001005,0.500588,0.501031,0.000000,0.000000,0.276123,0.388865,0.441677,0.489066,0.515361,0.122131,0.241924,0.393790,0.380330,0.283484,0.342070,0.437908,0.491451,0.522072,0.121263,0.181938,0.227634,0.388889,0.574074,0.446276,0.631461,0.246634,0.074440,0.579612,0.599041,0.153731,0.177014,0.578717,0.340582,0.136863,0.212446,0.576618,0.298702,0.168133,0.157396,0.559713,0.642447,0.066158,0.066158,0.119264,0.163685,0.163685,0.088629,0.214431,0.492661,0.461115,0.480347,0.485032,0.184106,0.280066,0.221554,0.239166,0.161162,0.110880,0.703865,0.164717,0.088173,1.000000,0.516555,0.426281,0.737681,0.084397,0.012055,49.739903,35.733383,25.920536,25.9250,0.255235,0.129425,0.413026,0.417079,0.418224,0.417052,0.417004,0.500800,0.317775,0.375501,0.543574,0.414255,0.333757,0.385547,0.363304,0.338824,0.324380,0.319855,0.370969,0.397194,0.318471,0.442464,0.366188,0.181382,0.402275,0.366967,0.575723,0.348621,0.199058,0.225999,0.253401,0.268967,0.695368,0.260432,0.773399,0.139556,0.714303,0.250423,0.317371,0.407460,0.499759,0.317371,0.428792,0.494092,0.306780,0.301635,0.306919,0.373692,0.419916,0.413333,0.492341,0.255943,0.814810,0.071429,0.565026,0.577456,0.844598,0.404628,0.328598,0.549616,0.516537,0.600198,0.305556,0.270833,0.500000,0.500000,0.508219,0.500000,0.0,1.0,0.0
2016-01-04 08:51:00,0.001607,0.000251,0.200801,0.201086,0.000000,0.000000,0.165850,0.207214,0.275368,0.375479,0.443925,0.079664,0.074948,0.203167,0.242846,0.197741,0.247589,0.273521,0.396332,0.453419,0.129880,0.008543,0.000000,0.277778,0.407407,0.277778,0.445665,0.277733,0.044167,0.380882,0.646671,0.184027,0.126747,0.443622,0.359715,0.154691,0.169936,0.493405,0.307640,0.179110,0.134000,0.510501,0.639370,0.090365,0.090365,0.120505,0.175188,0.175188,0.063763,0.079544,0.448966,0.419376,0.454435,0.466178,0.088427,0.152528,0.136308,0.140422,0.169661,0.116983,0.704629,0.226691,0.139919,1.000000,0.483061,0.345855,0.783344,0.038019,0.012790,49.537676,29.391936,25.920359,25.8975,0.389569,0.235918,0.445186,0.233004,0.519392,0.233439,0.232976,0.499760,0.037137,0.000000,0.470888,0.465029,0.330264,0.341806,0.316665,0.230482,0.000000,0.000000,0.355805,0.353778,0.304030,0.362351,0.326897,0.000000,0.366121,0.000000,0.547260,0.316515,0.169046,0.193485,0.219025,0.230220,0.488448,1.000000,0.544014,0.976233,0.660979,0.295988,0.000000,0.400667,0.371844,0.000000,0.436327,0.409447,0.315268,0.310578,0.309306,0.378290,0.419916,0.490173,0.492341,0.320197,0.814815,0.071429,0.743964,0.779697,1.000000,0.407441,0.276026,0.490033,0.698544,0.487260,0.306250,0.270833,0.500000,0.500000,0.508219,0.500000,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-13 15:41:00,0.048140,0.252952,0.455753,0.456192,0.076923,0.461538,0.159015,0.290940,0.264433,0.311224,0.411501,0.352968,0.126222,0.281211,0.349429,0.358049,0.269141,0.223650,0.212879,0.443028,0.234911,0.174937,0.134820,0.066709,0.175355,0.046814,0.149842,0.249020,0.042046,0.474546,0.626544,0.298142,0.119405,0.409722,0.268054,0.311233,0.172573,0.386119,0.119679,0.320115,0.188427,0.372182,0.093829,0.217292,0.217292,0.156300,0.318518,0.318518,0.318469,0.530643,0.491842,0.456144,0.510557,0.487361,0.344575,0.209853,0.179221,0.197037,0.312926,0.219851,0.153420,0.180505,0.287566,0.304381,0.245689,0.278073,0.385588,0.043395,0.218076,13.688595,41.248223,254.223349,252.1000,0.434130,0.394599,0.458535,0.425436,0.495734,0.425346,0.425423,0.499983,0.450737,0.468707,0.481227,0.451364,0.435667,0.428769,0.441853,0.459906,0.468746,0.474916,0.469840,0.406999,0.418457,0.413811,0.421654,0.446905,0.339762,0.478639,0.510914,0.339629,0.090144,0.131997,0.137767,0.132649,0.619691,0.345704,0.693338,0.272707,0.666011,0.264662,0.475241,0.523613,0.417758,0.475241,0.543462,0.403214,0.306525,0.313991,0.328537,0.353489,0.423509,0.527472,0.493019,0.466467,0.814805,0.071429,0.608099,0.592170,0.530878,0.381909,0.477321,0.627883,0.490629,0.495105,0.590972,0.562500,0.071429,0.666667,0.694521,0.692308,1.0,0.0,0.0
2026-03-13 15:42:00,0.079812,0.336096,0.500588,0.501031,0.615385,0.344615,0.158787,0.399293,0.323672,0.319582,0.411009,0.356161,0.126222,0.281211,0.349429,0.358049,0.434609,0.233683,0.241164,0.404037,0.309296,0.243394,0.198201,0.090518,0.103946,0.061950,0.077028,0.224689,0.031032,0.350237,0.683649,0.282481,0.107702,0.370269,0.296324,0.303122,0.162894,0.366783,0.131690,0.314497,0.180366,0.358686,0.100636,0.236176,0.236176,0.154609,0.312707,0.312707,0.525967,0.534173,0.520521,0.452551,0.478606,0.471560,0.503777,0.356750,0.295499,0.313311,0.312926,0.219851,0.153420,0.188996,0.278485,0.304398,0.247470,0.297208,0.385588,0.043395,0.214348,14.135917,41.248223,254.208979,252.1000,0.424494,0.396306,0.456642,0.426633,0.494755,0.426542,0.426620,0.500013,0.432039,0.457624,0.479935,0.453717,0.437273,0.421702,0.426674,0.450780,0.464502,0.472373,0.469765,0.419743,0.412442,0.460641,0.417408,0.433355,0.373687,0.470625,0.503170,0.333483,0.075980,0.116648,0.126671,0.119879,0.617091,0.346377,0.690241,0.274336,0.666382,0.266303,0.472565,0.521628,0.414483,0.472565,0.541344,0.399613,0.314973,0.313157,0.327428,0.351645,0.423590,0.518828,0.493019,0.466650,0.814805,0.071429,0.584024,0.582619,0.531155,0.435073,0.468337,0.614867,0.489202,0.488579,0.591667,0.562500,0.071429,0.666667,0.694521,0.692308,1.0,0.0,0.0
2026-03-13 15:43:00,0.089190,0.530771,0.310122,0.310500,0.000000,0.308462,0.238683,0.333013,0.247463,0.259210,0.364863,0.327317,0.057829,0.221355,0.305216,0.321099,0.363441,0.235553,0.172065,0.334619,0.254212,0.230545,0.173956,0.087935,0.081721,0.055387,0.054717,0.238521,0.019514,0.485810,0.757130,0.283073,0.091834,0.427275,0.336810,0.303123,0.149030,0.406333,0.149667,0.314403,0.168622,0.390973,0.111231,0.267663,0.267663,0.156118,0.312470,0.312470,0.321137,0.500740,0.486985,0.324233,0.442816,0.453391,0.475330,0.386568,0.309471,0.333020,0.319985,0.256861,0.153534,0.187945,0.278792,0.306277,0.228352,0.263659,0.414351,0.013913,0.214141,14.832151,38.515401,254.191880,251.9301,0.426560,0.387967,0.439331,0.403851,0.497529,0.403768,0.403834,0.499935,0.416579,0.448024,0.477918,0.455536,0.438510,0.405814,0.410854,0.436455,0.456879,0.468291,0.469378,0.405193,0.403400,0.444035,0.402916,0.419769,0.369115,0.459306,0.494187,0.314287,0.088710,0.115781,0.129157,0.123011,0.612301,0.348184,0.684445,0.277795,0.666067,0.267836,0.468473,0.517682,0.409661,0.468473,0.537239,0.394841,0.305509,0.311165,0.324042,0.350059,0.414505,0.489388,0.493085,0.458014,0.814805,0.071429,0.601725,0.609132,0.559099,0.455949,0.454447,0.597556,0.522518,0.483445,0.592361,0.562500,0.071429,0.666667,0.694521,0.692308,1.0,0.0,0.0
2026-03-13 15:44:00,0.070987,0.514444,0.264784,0.265129,0.115385,0.462308,0.307361,0.216046,0.151351,0.184031,0.308970,0.291163,0.028834,0.168576,0.258417,0.279831,0.253210,0.258236,0.226573,0.300380,0.123255,0.195360,0.134498,0.092160,0.090204,0.049172,0.055503,0.273564,0.011368,0.638661,0.823609,0.295546,0.075065,0.513538,0.388178,0.309489,0.132769,0.468910,0.174872,0.318709,0.154389,0.442697,0.126801,0.314567,0.314567,0.164151,0.316791,0.316791,0.187204,0.438796,0.470572,0.273326,0.411162,0.444788,0.333147,0.291421,0.235068,0.259554,0.354574,0.313693,0.182442,0.160413,0.287532,0.306313,0.203894,0.225060,0.449990,0.010448,0.216816,15.855250,35.463204,254.177195,251.7199,0.402314,0.366158,0.407501,0.375664,0.496581,0.375578,0.375657,0.499929,0.402642,0.436242,0.475106,0.456549,0.439079,0.382664,0.388536,0.420109,0.442796,0.462324,0.467992,0.377109,0.384646,0.405351,0.380150,0.403973,0.340754,0.444233,0.484422,0.283040,0.120854,0.131513,0.141004,0.133471,0.599762,0.351196,0.666388,0.283208,0.664439,0.269805,0.461869,0.510587,0.403277,0.461869,0.530143,0.388396,0.297971,0.308385,0.320374,0.348427,0.403771,0.444206,0.493145,0.443592,0.814805,0.071425,0.641469,0.644406,0.593212,0.414270,0.436155,0.577084,0.565197,0.476669,0.593056,0.562500,0.071429,0.666667,0.694521,0.692308,1.0,0.0,0.0
2026-03-13 15:45:00,0.049875,0.316001,0.455791,0.456230,0.307692,0.307692,0.125149,0.269304,0.199252,0.184023,0.299304,0.287256,0.025232,0.160010,0.250172,0.272375,0.227374,0.268253,0.247819,0.296751,0.189654,0.215327,0.167413,0.083518,0.087871,0.037692,0.047417,0.228470,0.009059,0.545531,0.868882,0.274465,0.069029,0.488497,0.433390,0.298459,0.126524,0.459326,0.198936,0.311083,0.148810,0.437129,0.142067,0.355891,0.355891,0.170779,0.308869,0.308869,0.178212,0.372583,0.460861,0.284936,0.365282,0.450969,0.261006,0.192921,0.166685,0.178710,0.361413,0.318614,0.185469,0.164751,0.287470,0.304245,0.200193,0.248097,0.456761,0.006955,0.211729,16.858419,34.911788,254.166801,251.6800,0.375447,0.346914,0.408185,0.371655,0.495026,0.371570,0.371647,0.500001,0.389481,0.421129,0.471893,0.457770,0.439609,0.368572,0.371614,0.406458,0.428850,0.455985,0.466252,0.372009,0.371173,0.431879,0.367719,0.390259,0.353467,0.431857,0.473974,0.269460,0.089622,0.114148,0.127012,0.117931,0.582364,0.353805,0.645107,0.287933,0.663114,0.271585,0.455080,0.504013,0.396028,0.455080,0.523619,0.380564,0.292669,0.301116,0.316408,0.346691,0.403363,0.440320,0.493165,0.443107,0.814805,0.071425,0.632732,0.643560,0.596929,0.393930,0.417892,0.557595,0.571662,0.466157,0.593750,0.562500,0.071429,0.666667,0.694521,0.692308,1.0,0.0,0.0

In [12]:
importlib.reload(plots)
plots.plot_dual_histograms(
    df_before = df_inds_rz,
    df_after  = df_feat_scal,
)

In [9]:
# Final Save
params.to_parquet_with_progress(df_feat_scal, params.feat_all_parquet)
print(f"✅ Feature Engineering Complete. File saved to {params.feat_all_parquet}")

Saving Parquet: 100%|██████████| 94/94 [00:19<00:00,  4.85it/s]

✅ Feature Engineering Complete. File saved to dfs/AAPL_3_feat_all.parquet

In [13]:
# --- DAILY PLOTS CHECK ---
# Filter for your check month (defined in params.py)
df_month = df_feat_scal[df_feat_scal.index.to_period('M') == params.month_to_check].copy()

for base_day, grp in df_month.groupby(df_month.index.normalize()):
    print('─' * 100)
    print(f"Chart for: {base_day.date()} | Features: {len(grp.columns)}")
    plots.plot_trades(
        df=grp,
        col_close='close_raw',
        features=list(grp.columns),
    )